using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using Newtonsoft.Json;

namespace ClassGenerator
{

    #region FontModel

    public class Jsonapi
    {
        public string version { get; set; }
    }

    public class Links
    {
        public string self { get; set; }
    }

    public class Price
    {
        public string currency { get; set; }
        public int amount { get; set; }
    }

    public class Membership
    {
        public List<string> pro { get; set; }
        public List<object> free { get; set; }
    }

    public class Attributes
    {
        public string sku { get; set; }
        public Price price { get; set; }
        public string name { get; set; }
        public string icon { get; set; }
        public string details { get; set; }
        public string category { get; set; }
        public string unicode { get; set; }
        public List<string> styles { get; set; }
        public Membership membership { get; set; }
        public string id { get; set; }
    }

    public class Datum
    {
        public string type { get; set; }
        public Links links { get; set; }
        public string id { get; set; }
        public Attributes attributes { get; set; }
    }

    public class Base
    {
        public Jsonapi jsonapi { get; set; }
        public List<Datum> data { get; set; }
    }

    public class RootObject
    {
        public List<Base> Base { get; set; }
    }

    #endregion

   

    class Program
    {
       
        static void Main(string[] args)
        {
            #region FontGenerator

            {
                var json = File.ReadAllText(@"c:\users\ershad\source\repos\ClassGenerator\ClassGenerator\fontAS.json");

                var model = Newtonsoft.Json.JsonConvert.DeserializeObject<RootObject>(json);


                string Solidcontent = "public class SolidFontawesome " + "\n" + "{\n";
                string Brandscontent = "public class BrandsFontawesome " + "\n" + "{\n";
                string RegularContent = "public class RegularFontawesome " + "\n" + "{\n";


                var SolidSource = model.Base[2].data.Where(x => x.attributes.styles.Contains("solid"));
                var RegularSource = model.Base[2].data.Where(x => x.attributes.styles.Contains("regular"));
                var BrandsSource = model.Base[2].data.Where(x => x.attributes.styles.Contains("brands"));


                Solidcontent += "\t public static string AndroidFontPath =" + "\"fa-solid-900.ttf#Font Awesome 5 Free Solid\"; \n";
                Solidcontent += "\t public static string IosFontPath =" + "\"Font Awesome 5 Free Solid\"; \n";

                RegularContent += "\t public static string AndroidFontPath =" + "\" fa-regular-400.ttf#Font Awesome 5 Free Regular\"; \n";
                RegularContent += "\t public static string IosFontPath =" + "\" Font Awesome 5 Free Regular\" ;\n";

                Brandscontent += "\t public static string AndroidFontPath =" + "\"fa-brands-400.ttf#Font Awesome 5 Free Brands\"; \n";
                Brandscontent += "\t public static string IosFontPath =" + "\"Font Awesome 5 Free Brands\" ;\n";


                foreach (var item in SolidSource)
                {
                    Solidcontent += "\t public static string " + item.attributes.styles[0] + "_" + item.id.Replace("-", "_") + " = " + "\"" + @"\u" + item.attributes.unicode + "\";\n";
                }
                Solidcontent += "}";

                foreach (var item in RegularSource)
                {
                    RegularContent += "\t public static string " + item.attributes.styles[0] + "_" + item.id.Replace("-", "_") + " = " + "\"" + @"\u" + item.attributes.unicode + "\";\n";
                }
                RegularContent += "}";


                foreach (var item in BrandsSource)
                {
                    Brandscontent += "\t public static string " + item.attributes.styles[0] + "_" + item.id.Replace("-", "_") + " = " + "\"" + @"\u" + item.attributes.unicode + "\";\n";
                }
                Brandscontent += "}";

                File.WriteAllText(@"\ClassGenerator\ClassGenerator\SolidAutoGenerated.cs", Solidcontent);
                File.WriteAllText(@"\ClassGenerator\ClassGenerator\BrandAutoGenerated.cs", Brandscontent);
                File.WriteAllText(@"\ClassGenerator\ClassGenerator\RegularAutoGenerated.cs", RegularContent);
            }

            #endregion




        }
    }
}
